// The Fibonacci Sequence is the series of numbers:
// 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// The first number in the sequence is 0, the second is 1, and each new term is generated by adding the previous two terms.

// Write a function to print (to the console) the first n terms in the fibonacci sequence
// Ex. n=5 produces '0, 1, 1, 2, 3'
// Ex. n=10 produces '0, 1, 1, 2, 3, 5, 8, 13, 21, 34'

function fibonacciCount(position: number) {
	let fibArrary: number[] = [0, 1];
	for (let i = fibArrary.length; i < position; i++) {
		fibArrary[i] = fibArrary[i - 2] + fibArrary[i - 1];
	}
	return fibArrary;
}

console.clear();
console.log('Fibbonacci(10): ');
console.log('Expected: ', '0, 1, 1, 2, 3, 5, 8, 13, 21, 34');
console.log('\n');
console.log('Result: ', fibonacciCount(10), ': ');
